### ISSUE TITLE
SVG logo doesn't appear in gmail

### ISSUE THREAD

**Issue by john-gom** [openfoodfacts/openfoodfacts-auth#131]
Probably need to switch to using an image data tag with a PNG or JPEG image

**Comment by hangy** [comment]
email templating is [a mess](https://css-tricks.com/a-guide-on-svg-support-in-email/) 😒

**Comment by john-gom** [comment]
Tried PNG logo and that didn't work either

**Comment by john-gom** [comment]
In the end had to use a static image from the server: https://static.openfoodfacts.org/images/logos/off-logo-horizontal-light.png 

Even static SVG didn't work
