### ISSUE TITLE
We must ask confirmation before removing an account

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-auth#148]
### What
Right now if you click on remove account, it's immediate without any confirmation which can lead to disasters.

### Solution

We must have a confirmation or at the very least a message to say that there is no such confirmation and that's its irreversible.

**Comment by john-gom** [comment]
Hi @alexgarel . There are a lot of confirmation steps in Keycloak for this. Are you jsut logging this issue to show that Keycloak resolves it or do you have concerns with the Keycloak implementation?

**Comment by alexgarel** [comment]
@john-gom I may have been misleaded yesterday by a quick test… it seemed to me as I clicked nothing was asked ! I will try again with a test account.

**Comment by alexgarel** [comment]
In fact, as you said @john-gom, there are a lot of caution… when I did my first test, I though I had been redirected to login because my account was removed, but on the contrary it asks you to login again to confirm removal. So that's perfectly fine. Thanks !
