### ISSUE TITLE
Design email verification and password reset emails

### ISSUE THREAD

**Issue by john-gom** [openfoodfacts/openfoodfacts-auth#32]
Add modified HTML templates from https://github.com/openfoodfacts/openfoodfacts-auth/tree/c833f3d370ca528069c7d4d335ea92d0698602d9/theme/base/email to https://github.com/openfoodfacts/openfoodfacts-auth/tree/c833f3d370ca528069c7d4d335ea92d0698602d9/theme/off and modify `messages` to match OFF wording.

Note: Keycloak doesn't provide a "sign-up" message per-se, but we want to use mail verification for new accounts, which could be used as a surrogate "welcome" mail

**Comment by john-gom** [comment]
I've noticed that the email is always in English and does not reflect my user's preferred language. @hangy is that the same for you?

**Comment by hangy** [comment]
Just tested on https://world.off.hangy.de/ and the German locale I selected for my account seems to work:

![image](https://github.com/user-attachments/assets/7680a24a-90c5-4064-bcd4-122557f792da)

**Comment by john-gom** [comment]
Ok. I wonder if the message strings are coming from a different place than for the themes. I was using a dummy language XX that isn't in the standard keycloak list of locales

**Comment by hangy** [comment]
Update after today's discussion: The welcome mail could be sent by ProductOpener using the existing mechanism. To do that, Keycloak should publish a new "user created" event as soon as the user account is usable (ie. email should likely be validated, _if_ mail validation is enabled)

**Comment by john-gom** [comment]
Renamed issue to just cover the email verification and password reset emails
