### ISSUE TITLE
Ensure "Back to Application" links are available everywhere

### ISSUE THREAD

**Issue by john-gom** [openfoodfacts/openfoodfacts-auth#36]

**Comment by hangy** [comment]
@john-gom The existing "backToApplication" links redirect back to the originating OIDC client. I guess the idea of this suggestion is to have a link "back" to OpenFoodFacts/OpenProductFacts when in the "account console", for example?

**Comment by john-gom** [comment]
Yes. Even if you log out it should take you back to the main web page, rather than prompting for a user id and password again. And we should always be able to get back to the web page at any point

**Comment by hangy** [comment]
The built-in "Back to application" link always sends you back to the application that initiated the sign-in. The places that don't have a "back" link now, are often not initiated from an OIDC client app, I think. Maybe we could just add a "Go to OpenFoodFacts" link to a base template?

**Comment by john-gom** [comment]
I noticed that from the Account Preferences in Keycloak the OFF logo in the top left tries to log into the Keycloak Master realm. This needs to go back to the main OFF web site

**Comment by hangy** [comment]
I searched through the Keycloak sources a bit and found a native Keycloak feature we could use.
By adding `referrer_uri` and  `referrer` (ClientId)parameters to the account console, by default, we get the following link to be displayed: ![screenshot of the Keycloak account console header with a link back to the ProductOpener client](https://github.com/user-attachments/assets/4d689790-ac39-49a4-b860-7902d2b9c0ab) The link will lead the user back to the `referrer_uri`. Unfortunately, it looks like wildcards for valid redirect URIs are only supported for the path, not the hostname: ![screenshot of the Keycloak admin console with configured redirect URIs for the ProductOpener client](https://github.com/user-attachments/assets/21f6bdd5-55ad-4b1f-93db-1f390015dc43) Adding all language/country combos might be a bit excessive.

I wonder if overriding the `logoUrl` with `referrerUrl` (when available) could lead the logo to forward the user to the correct OIDC RP https://github.com/openfoodfacts/openfoodfacts-auth/blob/0403d31207916c1ae8f30acab285ffd593072257/theme/keycloak.v3/account/index.ftl#L120-L124

**Comment by hangy** [comment]
I think this should be good now
