### ISSUE TITLE
Intuitive editing of preferences vs security parameters

### ISSUE THREAD

**Issue by john-gom** [openfoodfacts/openfoodfacts-auth#37]

**Comment by hangy** [comment]
Right now, the only user-configurable settings are
- joining an org for producer accounts,
- Display barcode in search results
- Add an edit link in search results

My understanding is that org management has been moved to MongoDB. Therefore, it's not really a task for Keycloak.

The barcode and edit link could be seen as site-specific/client-specific/app-specific setting, which isn't necessarily a task for Keycloak? Right now, we're not getting rid of `user.sto` entirely (I'd like to not touch HTTP session handling for the first iteration), so we could just keep these settings as-is.

**Comment by john-gom** [comment]
Hi @hangy . I think my main concern here is one of usability - it is not very nice at the moment to have one page for the above settings and then a different page (inside Keycloak) for things like changing your name and password.

**Comment by hangy** [comment]
It's a bit of a philosophical question, IMHO. The way I see it, lots of big sites (think Microsoft or Google) have central settings and maybe something like RBAC in an "account website" such as Keycloak, but if you want to configure your Gmail/Outlook mail settings, you use a separate UI in that application. Likewise, the "display barcode in search results" settings is specific to ProductOpener and irrelevant to the mobile apps, or Robotoff/Hunger Games, for example.

As the settings that are specific to ProductOpener are very few now, they might just be toggles on the search results page, for example

**Comment by john-gom** [comment]
Hi @hangy . I'm happy if we want to move the barcode and edit link settings to somewhere where it is easier to toggle them, but I think having a specific settings page that just shows these two settings and then another button to get to the Keycloak page is pretty messy.

I guess the other way to do it would be to have two options when you click on your name:

- Account Parameters (the current option which would now go straight to Keycloak)
- Preferences (new option which would just show product specific settings

![image](https://github.com/user-attachments/assets/4f4f6e46-4e6b-4f62-9376-c386fd1c9b7a)

What do you think?

**Comment by hangy** [comment]
Yes, something like that was what I had in mind. Admins might have to deal with the complicated "parameters" page for bot/moderator/… for a while, but we really can't do everything in one go
