### ISSUE TITLE
Pass fields from "register to newsletter" and "I'm a producer" from user.pl to Keycloak

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-auth#86]
When creating a new user from `register.pl` with the compatibility mode, forward all fields including "register to newsletter" and "I'm a producer" to Keycloak, and ensure the do the right thing(TM) in Keycloak.

tbd: `register.pl` as discussed in the 2024-09-23 meeting doesn't exist. Most likely candidate is `user.pl`. Investigate API usage of that CGI script.

**Comment by john-gom** [comment]
Current plan for organisations:

1. We add a field on the sign-up form where the user can optionally specify what producer organisation they are a member of (note the basic Keycloak fields don't allow the checkbox and then conditionally displaying the organisation name field, so we would just ask for the requested organisation name and leave blank if not a producer)
2. There will initially be no specific feedback to the user if they have done this. They validate their email and then get redirected to the main landing page like any other user. However, behind the scenes, once the email is validated, we will add the user to the requested organisation and notify the administrator as we currently do (call Perl process_user_requested_org)
3. The existing process of accepting a user into the organisation (org.pl) will remain unchanged, i.e. the master source of truth for organisation membership will still be Product Opener
4. The "requested organisation" field in Keycloak will not be displayed for existing users (as it might be out of sync with what has been approved).
5. The existing Preferences page will continue to show the text about organisation membership status, and allow this to be edited, if this would have been allowed before

**Comment by john-gom** [comment]
@hangy , I'm concerned we might create unnecessary repeated steps with the newsletter and producer fields with support for the old user.pl "API".

At the moment we have two ways of creating users (1) via the Keycloak and (2) with the user.pl form called as an API. For case 1 the steps would be:

1. User enters their details in Keycloak
2. Keycloak sends address validation email
3. User clicks on the link in the email
4. Keycloak creates the user-registered Redis event
5. Product Opener receives this event and sends the welcome email and optionally signs the user up to the newsletter and registers them as a producer

For case 2 the details are all entered via the external system (e.g. the mobile app) and we have decided that we don't want email verification in this case for now. So, the steps are:

1. User enters their details in the external app
2. App calls user.pl to create the user
3. Product Opener creates the user in Keycloak with email verified
4. Keycloak creates the user-registered Redis event
5. Product Opener receives this event and sends the welcome email and optionally signs the user up to the newsletter and registers them as a producer

This basically works, the only complication is that user.pl can also be used as the "Preferences" page to edit Producer information (as we aren't showing this data in Keycloak for editing). I'm therefore proposing that we keep some of the producer code running at the user.pl path when the user is being edited.

Does this make sense?

**Comment by hangy** [comment]
Yes that sounds reasonable. As long as we only have one place for everything (at least to actually fulfill the task), I don't see any potential issues
