### ISSUE TITLE
Publish "user created" event - ideally after a user was fully created in Keycloak

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-auth#88]
When a user was fully created in Keycloak - if email validation is enabled, then this should likely be after that - send a "user created" event with necessary information to the Redis stream.

**Comment by john-gom** [comment]
@hangy I had to make some changes to the Java code to also respond to "Admin" events as these are what we get when Product Opener creates the user in Keycloak. I've only got end to end (playwright) tests for this at the moment but feel free to add some unit tests if you feel they are needed :-)
